Exception ignored in: <module 'threading' from '/home/bs6865/.conda/envs/ldb/lib/python3.10/threading.py'>
Traceback (most recent call last):
  File "/home/bs6865/.conda/envs/ldb/lib/python3.10/threading.py", line 1567, in _shutdown
    lock.acquire()
KeyboardInterrupt: 

real	16m14.933s
user	15m18.470s
sys	0m1.673s
